version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ../data/tasks/:/var/lib/postgresql/data/
    networks:
      - task_network

  backend:
    container_name: backend
    env_file:
      - .env
    build:
      context: ./backend
      args:
        db_url: ${DATABASE_URL}
    ports:
      - 3000:3000
      - 5555:5555 #for npx prisma studio
    networks:
      - task_network
    depends_on:
      - postgres

networks:
  task_network:

